package com.creative.shoppinglist.ui.components

object TestTags {
    const val FAB_ADD_ITEM = "FAB_ADD_ITEM"
    const val BOTTOM_SHEET_ADD_ITEM = "BOTTOM_SHEET_ADD_ITEM"
    const val ITEM_NAME_INPUT = "ITEM_NAME_INPUT"
    const val ITEM_IMPORTANT_SWITCH = "ITEM_IMPORTANT_SWITCH"
    const val ITEM_REMINDER_SWITCH = "ITEM_REMINDER_SWITCH"
    const val ITEM_REMINDER_BUTTON = "ITEM_REMINDER_BUTTON"
    const val SAVE_ITEM_BUTTON = "SAVE_ITEM_BUTTON"
    const val EMPTY_SCREEN_ADD_BUTTON = "EMPTY_SCREEN_ADD_BUTTON"
    const val BOTTOM_NAV_ITEM = "BOTTOM_NAV_ITEM_"
    const val SHOPPING_ITEM_CHECKBOX = "SHOPPING_ITEM_CHECKBOX_"
    const val SHOPPING_ITEM_DELETE = "SHOPPING_ITEM_DELETE_"
    const val DATE_PICKER_CONFIRM = "DATE_PICKER_CONFIRM"
    const val TIME_PICKER_CONFIRM = "TIME_PICKER_CONFIRM"
}
